import type { Metadata } from "next";
import Image from "next/image";
import { Eye, Handshake, MessageSquare, ShieldCheck, Target, Wrench } from "lucide-react";
import { AudienceGrid, CTASection, CheckList, PageHero, ProcessStrip } from "@/components/sections";
import { Container, SectionHeading } from "@/components/ui";
import { company } from "@/data/company";

export const metadata: Metadata = { title: "About Us", description: "Learn about Pro Property Care Solutions LLC’s mission, approach, clients, and commitment to professional property support." };

export default function AboutPage() { return <>
  <PageHero eyebrow="ABOUT PRO PROPERTY CARE" title="A property-care partner built for follow-through." copy="We support the people responsible for keeping residential and commercial properties safe, functional, clean, and ready for what comes next." image="https://images.unsplash.com/photo-1521791055366-0d553872125f?auto=format&fit=crop&w=1600&q=85"/>
  <section className="section about-intro"><Container><div><SectionHeading eyebrow="OUR COMPANY" title="Practical capability, centered on the property." copy="Pro Property Care Solutions LLC is structured to address a wide range of maintenance, repair, turnover, and grounds-care needs. Our goal is to make property work easier to coordinate and easier to trust."/><p>Whether the need is a single repair, a vacancy turnaround, recurring upkeep, or a varied punch list, we focus on understanding the scope, communicating clearly, and caring for the property throughout the work.</p></div><div className="about-image"><Image src="https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1400&q=85" alt="Property service professionals reviewing project details" fill sizes="(max-width: 900px) 100vw, 45vw"/></div></Container></section>
  <section className="mission-section"><Container><div><Target/><span className="eyebrow light">OUR MISSION</span><h2>To deliver dependable, well-coordinated property services that help clients protect, prepare, and care for every property entrusted to them.</h2></div><div><p>That means practical service, responsive communication, and attention to the details that affect safety, usability, presentation, and value.</p><CheckList items={["Be clear about scope and expectations", "Respect the property and its occupants", "Coordinate work with practical efficiency", "Follow through and communicate progress"]}/></div></Container></section>
  <section className="section"><Container><SectionHeading eyebrow="WHO WE SERVE" title="Support that adapts to the client and the property." align="center"/><AudienceGrid/></Container></section>
  <section className="section approach-section"><Container><SectionHeading eyebrow="OUR APPROACH" title="Professional property care without unnecessary complexity." copy="A simple operating approach keeps the work understandable from the first conversation through completion."/><ProcessStrip/></Container></section>
  <section className="section values-section"><Container><SectionHeading eyebrow="WHY CLIENTS CHOOSE US" title="The standards behind the service."/><div className="values-grid">{[[Handshake,"One reliable relationship","A broad service range helps reduce vendor coordination."],[MessageSquare,"Responsive communication","Clear updates keep owners and managers informed."],[Wrench,"Practical capability","Support for repairs, turns, upkeep, and grounds needs."],[Eye,"Attention to detail","A quality-focused eye for function and presentation."],[ShieldCheck,"Professional care","Respect for the property, the scope, and the people involved."]].map(([Icon,t,c]) => <article key={t as string}><Icon/><h3>{t as string}</h3><p>{c as string}</p></article>)}</div></Container></section>
  <section className="credentials-section"><Container><div><span className="eyebrow">SERVICE AREA</span><h2>Coverage details</h2><p>{company.serviceArea}</p><small>Update in src/data/company.ts before launch.</small></div><div className="credential-list"><article><b>Licensing</b><span>{company.licenseStatus}</span></article><article><b>Insurance</b><span>{company.insuranceStatus}</span></article><article><b>Bonding</b><span>{company.bondingStatus}</span></article></div></Container></section>
  <CTASection/>
  </> }
