import Image from "next/image";
import Link from "next/link";
import { ArrowRight, CheckCircle2, MessageSquareText, ShieldCheck } from "lucide-react";
import { Button, Container, SectionHeading } from "@/components/ui";
import { AudienceGrid, CheckList, CTASection, TrustStrip } from "@/components/sections";
import { serviceGroups } from "@/data/services";
import { reviews, reviewDisclaimer } from "@/data/reviews";
import { company } from "@/data/company";
import { HomeMotion } from "@/components/home-motion";
import { StatsCounter } from "@/components/stats-counter";

export default function Home() {
  const heroLineOne = ["Complete", "Property", "Care."];
  const heroLineTwo = ["One", "Reliable", "Partner."];
  return <>
    <HomeMotion/>
    <section className="hero"><Image className="hero-bg" src="https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=2400&q=90" alt="Professionally maintained residential property" fill priority sizes="100vw"/><div className="hero-overlay"/><Container><div className="hero-content"><span className="eyebrow light">PROPERTY MAINTENANCE YOU CAN RELY ON</span><h1>{heroLineOne.map((word,index) => <span className="hero-word" style={{ animationDelay: `${0.22 + index * 0.28}s` }} key={word}>{word}{index < heroLineOne.length - 1 ? " " : ""}</span>)}<br/><em>{heroLineTwo.map((word,index) => <span className="hero-word" style={{ animationDelay: `${1.06 + index * 0.28}s` }} key={word}>{word}{index < heroLineTwo.length - 1 ? " " : ""}</span>)}</em></h1><p>Dependable residential and commercial maintenance, repairs, turnover services, grounds care, and practical property solutions—all coordinated with clear communication.</p><div className="button-row"><Button href="/contact" variant="light">Get a Free Quote</Button></div></div><div className="hero-note"><ShieldCheck/><span><b>Professional property care</b><small>Built around reliability, responsiveness, and quality-focused work.</small></span></div></Container></section>
    <TrustStrip/>
    <StatsCounter/>
    <section className="section services-preview" data-reveal="up"><Container><SectionHeading eyebrow="COMPLETE PROPERTY SUPPORT" title="One partner for the work that keeps properties moving." copy="From recurring maintenance and turnovers to interior repairs and grounds care, our service model is designed to reduce coordination and keep priorities clear."/><div className="services-grid">{serviceGroups.map(({icon: Icon,...group}, i) => <article key={group.title} data-reveal="up" className={`service-card ${i === 0 ? "featured" : ""}`}><span className="service-icon"><Icon/></span><span className="service-number">0{i+1}</span><h3>{group.title}</h3><p>{group.description}</p><ul>{group.services.slice(0,4).map(x => <li key={x}>{x}</li>)}</ul><Link href={`/services#${group.slug}`}>Explore services <ArrowRight size={16}/></Link></article>)}</div><div className="section-link"><Link href="/services">Explore All Services <ArrowRight/></Link></div></Container></section>
    <section className="section split-section" data-reveal="up"><Container><div className="split-images" data-reveal="left"><div className="image-main"><Image src="https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1400&q=85" alt="Property professional reviewing work on site" fill sizes="(max-width: 900px) 100vw, 46vw"/></div><div className="image-accent"><Image src="https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=700&q=85" alt="Careful property cleaning and preparation" fill sizes="260px"/></div><div className="image-badge"><CheckCircle2/><b>One accountable partner</b><span>For details large and small</span></div></div><div data-reveal="right"><SectionHeading eyebrow="WHY PRO PROPERTY CARE" title="Practical service. Professional follow-through." copy="Property work gets complicated when every task requires a new vendor. We bring a broad range of everyday property needs under one responsive relationship."/><CheckList items={["Residential and commercial capability", "Support for recurring and one-time needs", "Clear, responsive communication", "Quality-focused workmanship", "Flexible support for managers and owners"]}/><Button href="/about">How We Work</Button></div></Container></section>
    <section className="manager-section" data-reveal="up"><Container><div data-reveal="left"><span className="eyebrow light">BUILT FOR PROPERTY OPERATIONS</span><h2>A capable extension of your property management team.</h2><p>Keep turnovers, recurring upkeep, property securing, repairs, trash-outs, and grounds care moving through one reliable point of contact.</p><CheckList items={["Turnovers and unit preparation", "Recurring maintenance support", "Trash-outs and clean-outs", "Repairs and property securing", "Exterior and grounds care"]}/><Button href="/contact" variant="light">Discuss Your Property Needs</Button></div><div className="manager-image" data-reveal="right"><Image src="https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1400&q=85" alt="Property manager holding keys at a managed property" fill sizes="(max-width: 900px) 100vw, 50vw"/></div></Container></section>
    <section className="section audience-section" data-reveal="up"><Container><SectionHeading eyebrow="WHO WE SERVE" title="Responsive support for every kind of property stakeholder." align="center"/><AudienceGrid/></Container></section>
    <section className="section testimonials-section" data-reveal="up"><Container><div className="heading-row"><SectionHeading eyebrow="CLIENT EXPERIENCE" title="The kind of service relationships we aim to build." copy="Clear communication, practical coordination, and respect for the property at every step."/><MessageSquareText size={54}/></div><div className="testimonial-grid">{reviews.slice(0,3).map((r) => <blockquote key={r.name} data-reveal="up"><div className="stars" aria-label={`${r.rating} out of 5 stars`}><span>{"★".repeat(r.rating)}</span><span className="empty">{"★".repeat(5-r.rating)}</span></div><p>“{r.text}”</p><footer><span>{r.initials}</span><div><b>{r.name}</b><small>{r.type}</small></div></footer></blockquote>)}</div><p className="disclaimer">{reviewDisclaimer}</p></Container></section>
    <section className="service-area" data-reveal="up"><Container><div data-reveal="left"><span className="eyebrow">SERVICE AREA</span><h2>Need dependable property maintenance in your area?</h2><p>Contact us to confirm coverage for your property and discuss the service you need.</p></div><div data-reveal="right"><b>Current coverage information</b><span>{company.serviceArea}</span><Button href="/contact">Check Availability</Button></div></Container></section>
    <CTASection/>
  </>;
}
