import Image from "next/image";
import Link from "next/link";
import { ArrowRight, CheckCircle2, MessageSquareText, ShieldCheck } from "lucide-react";
import { Button, Container, SectionHeading } from "@/components/ui";
import { AudienceGrid, CheckList, CTASection, ProjectCard, TrustStrip } from "@/components/sections";
import { serviceGroups } from "@/data/services";
import { projects } from "@/data/projects";
import { reviews, reviewDisclaimer } from "@/data/reviews";
import { company } from "@/data/company";

export default function Home() {
  return <>
    <section className="hero"><Image className="hero-bg" src="https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=2400&q=90" alt="Professionally maintained residential property" fill priority sizes="100vw"/><div className="hero-overlay"/><Container><div className="hero-content"><span className="eyebrow light">PROPERTY MAINTENANCE YOU CAN RELY ON</span><h1>Complete Property Care.<br/><em>One Reliable Partner.</em></h1><p>Dependable residential and commercial maintenance, repairs, turnover services, grounds care, and practical property solutions—all coordinated with clear communication.</p><div className="button-row"><Button href="/contact" variant="light">Get a Free Quote</Button><Button href="/projects" variant="outline">View Our Work</Button></div></div><div className="hero-note"><ShieldCheck/><span><b>Professional property care</b><small>Built around reliability, responsiveness, and quality-focused work.</small></span></div></Container></section>
    <TrustStrip/>
    <section className="section services-preview"><Container><SectionHeading eyebrow="COMPLETE PROPERTY SUPPORT" title="One partner for the work that keeps properties moving." copy="From recurring maintenance and turnovers to interior repairs and grounds care, our service model is designed to reduce coordination and keep priorities clear."/><div className="services-grid">{serviceGroups.map(({icon: Icon,...group}, i) => <article key={group.title} className={`service-card ${i === 0 ? "featured" : ""}`}><span className="service-icon"><Icon/></span><span className="service-number">0{i+1}</span><h3>{group.title}</h3><p>{group.description}</p><ul>{group.services.slice(0,4).map(x => <li key={x}>{x}</li>)}</ul><Link href={`/services#${group.slug}`}>Explore services <ArrowRight size={16}/></Link></article>)}</div><div className="section-link"><Link href="/services">Explore All Services <ArrowRight/></Link></div></Container></section>
    <section className="section split-section"><Container><div className="split-images"><div className="image-main"><Image src="https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1400&q=85" alt="Property professional reviewing work on site" fill sizes="(max-width: 900px) 100vw, 46vw"/></div><div className="image-accent"><Image src="https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=700&q=85" alt="Careful property cleaning and preparation" fill sizes="260px"/></div><div className="image-badge"><CheckCircle2/><b>One accountable partner</b><span>For details large and small</span></div></div><div><SectionHeading eyebrow="WHY PRO PROPERTY CARE" title="Practical service. Professional follow-through." copy="Property work gets complicated when every task requires a new vendor. We bring a broad range of everyday property needs under one responsive relationship."/><CheckList items={["Residential and commercial capability", "Support for recurring and one-time needs", "Clear, responsive communication", "Quality-focused workmanship", "Flexible support for managers and owners"]}/><Button href="/about">How We Work</Button></div></Container></section>
    <section className="section projects-preview"><Container><div className="heading-row"><SectionHeading eyebrow="SELECTED WORK" title="Property care, seen in the details." copy="A preview of the types of maintenance, preparation, and improvement work we support."/><Button href="/projects" variant="outline">View All Projects</Button></div><div className="project-preview-grid">{projects.slice(0,3).map(p => <ProjectCard project={p} key={p.id}/>)}</div></Container></section>
    <section className="manager-section"><Container><div><span className="eyebrow light">BUILT FOR PROPERTY OPERATIONS</span><h2>A capable extension of your property management team.</h2><p>Keep turnovers, recurring upkeep, property securing, repairs, trash-outs, and grounds care moving through one reliable point of contact.</p><CheckList items={["Turnovers and unit preparation", "Recurring maintenance support", "Trash-outs and clean-outs", "Repairs and property securing", "Exterior and grounds care"]}/><Button href="/contact" variant="light">Discuss Your Property Needs</Button></div><div className="manager-image"><Image src="https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1400&q=85" alt="Property manager holding keys at a managed property" fill sizes="(max-width: 900px) 100vw, 50vw"/></div></Container></section>
    <section className="section audience-section"><Container><SectionHeading eyebrow="WHO WE SERVE" title="Responsive support for every kind of property stakeholder." align="center"/><AudienceGrid/></Container></section>
    <section className="section testimonials-section"><Container><div className="heading-row"><SectionHeading eyebrow="CLIENT EXPERIENCE" title="The kind of service relationships we aim to build." copy="Clear communication, practical coordination, and respect for the property at every step."/><MessageSquareText size={54}/></div><div className="testimonial-grid">{reviews.slice(0,3).map((r,i) => <blockquote key={r.name}><div className="stars" aria-label="Five stars">★★★★★</div><p>“{r.text}”</p><footer><span>{r.initials}</span><div><b>{r.name}</b><small>{r.type}</small></div></footer>{i === 0 && <em>Sample content</em>}</blockquote>)}</div><p className="disclaimer">{reviewDisclaimer}</p></Container></section>
    <section className="service-area"><Container><div><span className="eyebrow">SERVICE AREA</span><h2>Need dependable property maintenance in your area?</h2><p>Contact us to confirm coverage for your property and discuss the service you need.</p></div><div><b>Current coverage information</b><span>{company.serviceArea}</span><Button href="/contact">Check Availability</Button></div></Container></section>
    <CTASection/>
  </>;
}
