import type { Metadata } from "next";
import { MessageSquareQuote, Star } from "lucide-react";
import { CTASection, PageHero } from "@/components/sections";
import { Container, SectionHeading } from "@/components/ui";
import { reviewDisclaimer, reviews } from "@/data/reviews";

export const metadata: Metadata = { title: "Client Reviews", description: "Read sample client experience content for Pro Property Care Solutions LLC." };

export default function ReviewsPage() { return <><PageHero eyebrow="CLIENT EXPERIENCE" title="Trust is built through the work—and the follow-through." copy="We aim to make every interaction clear, professional, and dependable, whether the scope is one repair or an ongoing portfolio relationship." image="https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1600&q=85"/><section className="review-trust"><Container><div><MessageSquareQuote/><span className="eyebrow light">OUR SERVICE STANDARD</span><h2>Responsive. Practical. Property-focused.</h2></div><p>Strong property-service relationships come from showing up prepared, communicating clearly, respecting the site, and completing the agreed scope with care.</p><div className="review-principles"><span>Clear communication</span><span>Professional conduct</span><span>Quality-focused work</span></div></Container></section><section className="section reviews-page"><Container><SectionHeading eyebrow="CUSTOMER EXPERIENCES" title="Property care built around clear communication." copy="Feedback from homeowners, property managers, real estate professionals, and investors across different types of property work."/><div className="reviews-grid">{reviews.map((r) => <blockquote key={r.type}><div className="review-stars" aria-label={`${r.rating} out of 5 stars`}>{Array.from({length:5},(_,index) => <Star key={index} className={index < r.rating ? "filled" : "empty"} fill="currentColor"/>)}</div><p>“{r.text}”</p><footer><span>{r.initials}</span><div><b>{r.name}</b><small>{r.type}</small></div></footer></blockquote>)}</div><p className="disclaimer prominent">{reviewDisclaimer}</p></Container></section><CTASection title="Ready for a more dependable property-care experience?" copy="Tell us what needs attention and let’s start with a clear conversation."/></> }
